###############################################################
### Request del usuario
###############################################################
GET http://localhost:8888/usuario

###############################################################
### Request del usuario con nombre
###############################################################
GET http://localhost:8888/usuario/pedro

###############################################################
### Request del usuario con nombre y apellido
###############################################################
GET http://localhost:8888/usuario/pedro/perez