### Operaciones CRUD -> Create, Read, Update, Delete

### Obtener todas las lista de tareas
GET /to-do
Host: localhost:4040

### Crear una tarea
POST /to-do
Host: localhost:4040
Content-Type: application/json

{
    "title": "Ejemplo",
    "text": "Esto es una tarea de ejemplo",
    "importance": 4
}

### Actualizar una tarea
PUT /to-do/?title=Ejemplo
Host: localhost:4040
Content-Type: application/json

{
    "title": "Otro Ejemplo",
    "text": "Esto es una tarea del otro ejemplo",
    "importance": 1
}

### Eliminar la tarea
DELETE /to-do?title=Otro Ejemplo
Host: localhost:4040

